import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  pdf,
} from "@react-pdf/renderer";
import path from "path";
import { writeFile, mkdir } from "fs/promises";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: "Helvetica",
    fontSize: 11,
  },
  title: {
    fontSize: 16,
    marginBottom: 16,
    fontWeight: "bold",
  },
  paragraph: {
    marginBottom: 12,
    lineHeight: 1.5,
  },
  listItem: {
    marginLeft: 12,
    marginBottom: 6,
  },
  footer: {
    marginTop: 24,
    fontSize: 9,
    color: "#64748b",
  },
});

type LetterParams = {
  letterType: string;
  clientName: string;
  clientAddress: string;
  negativeItems: Array<{
    accountName: string;
    bureau: string;
    negativeReason: string;
  }>;
};

function LetterDocument({ params }: { params: LetterParams }) {
  const { letterType, clientName, clientAddress, negativeItems } = params;

  const titles: Record<string, string> = {
    bureau: "Credit Bureau Dispute Letter",
    mov: "Method of Verification Request",
    creditor: "Creditor Direct Dispute Letter",
    cfpb: "CFPB Complaint Draft",
  };

  const intros: Record<string, string> = {
    bureau: `I am writing to dispute inaccurate information on my credit report. I have reviewed my report and found the following item(s) that I believe are incorrect or incomplete. Please investigate and correct or remove these items as required under the FCRA.`,
    mov: `Under the Fair Credit Reporting Act, I am requesting the method of verification used to confirm the following account(s). Please provide the details of how you verified this information with the furnisher.`,
    creditor: `I am writing to dispute the following information that your company has furnished to the consumer reporting agencies. Under the FCRA, you must investigate and correct or delete inaccurate information.`,
    cfpb: `I am filing this complaint regarding the following credit reporting inaccuracies. I have attempted to resolve these issues through the credit bureaus and/or furnisher without satisfactory resolution.`,
  };

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{titles[letterType] ?? "Dispute Letter"}</Text>
        <Text style={styles.paragraph}>
          {new Date().toLocaleDateString("en-US", {
            year: "numeric",
            month: "long",
            day: "numeric",
          })}
        </Text>
        <Text style={styles.paragraph}>
          Re: Dispute — {clientName}
          {clientAddress}
        </Text>
        <Text style={styles.paragraph}>{intros[letterType] ?? intros.bureau}</Text>
        <Text style={styles.paragraph}>Disputed items:</Text>
        {negativeItems.map((item, i) => (
          <View key={i} style={styles.listItem}>
            <Text>
              • {item.accountName} — Bureau: {item.bureau}
              {item.negativeReason ? ` — ${item.negativeReason}` : ""}
            </Text>
          </View>
        ))}
        <Text style={styles.paragraph}>
          Please conduct a reasonable investigation and provide me with written
          results within 30 days as required by law.
        </Text>
        <Text style={styles.footer}>
          Generated by CreditLyft Portal. This is a draft; review and customize
          before sending.
        </Text>
      </Page>
    </Document>
  );
}

export async function generateLetterPdf(
  params: LetterParams
): Promise<string | null> {
  try {
    const blob = await pdf(<LetterDocument params={params} />).toBlob();
    const buffer = Buffer.from(await blob.arrayBuffer());
    const dir = path.join(process.cwd(), "uploads", "letters");
    await mkdir(dir, { recursive: true });
    const fileName = `letter-${params.letterType}-${Date.now()}.pdf`;
    const filePath = path.join(dir, fileName);
    await writeFile(filePath, buffer);
    return path.relative(process.cwd(), filePath);
  } catch (e) {
    console.error("Letter PDF failed:", e);
    return null;
  }
}
